

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo in ubuntu
      uses: actions/checkout@v3
      
    - name: Display the Repo content
      run: |
        mvn -version
        pwd
        ls -lrth
     
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Validating POM XML File
      run: |
        mvn validate
        ls -lrth
      
    - name: Compile the code
      run: |
        ls -lrth
        mvn compile
        ls -lrth
    
    - name: Test the code
      run: |
        ls -lrth
        mvn test
        ls -lrth
      
    - name: Clean the code
      run: |
        ls -lrth
        mvn clean 
        ls -lrth
      
    - name: Create a new package
      run: |
        mvn package
        ls -lrth target/
        
    - name:  Priniting message command 
      run: |
        java -cp target/mavendemoapp-1.0-SNAPSHOT.jar com.example.demo.App
        
    - name: Artifact upload process in workflow
      uses: actions/upload-artifact@v3
      with:
          name: maven-artifact
          path: target/mavendemoapp-1.0-SNAPSHOT.jar    
      

